
common: &common
      app: website
      repository: git@github.com:davidahopp/website.git
      shared_paths: ['config/database.yml', 'log', 'config/secrets.yml']
production:
      <<: *common
      domain: 107.170.101.157
      user: sitedeploy
      branch: production



